'use strict';
const path=require('path');const docs=require('./agent-documents');
const guides=[
 {slug:'jesus-buen-pastor',title:'Jesús, el Buen Pastor',reference:'Juan 10, 11-16',source:'https://press.vatican.va/content/francesco/es/angelus/2018/documents/papa-francesco_regina-coeli_20180422.pdf',objective:'Reconocer la imagen del Buen Pastor como expresión del amor y del cuidado de Jesús.',explanation:'Jesús se presenta como el Buen Pastor que conoce a sus ovejas y da su vida por ellas. La imagen del pastor ayuda a comprender su amor. El dibujo es una representación artística del pasaje, no una fotografía histórica.',questions:['¿Cómo cuida el pastor a sus ovejas?','¿Qué enseña Jesús sobre su amor en este pasaje?','¿Cómo podemos cuidar hoy a alguien de nuestra familia?'],activity:'Colorea el dibujo. Después, señala tres detalles que expresen cuidado. Elige una acción concreta para ayudar en casa esta semana.',evaluation:'Invita al niño a explicar con sus palabras por qué llamamos a Jesús Buen Pastor. Escucha sin exigir que memorice la explicación.'},
 {slug:'jesus-bendice-ninos',title:'Jesús bendice a los niños',reference:'Marcos 10, 13-16',source:'https://bible.usccb.org/bible/mark/10',objective:'Descubrir que Jesús acoge a los niños y aprender a recibir a los demás con respeto.',explanation:'En este pasaje, algunas personas llevan niños a Jesús. Él pide que los dejen acercarse, los abraza y los bendice. La escena muestra su acogida. El dibujo es una representación artística; los rostros y el paisaje no son datos del Evangelio.',questions:['¿Quiénes querían acercarse a Jesús?','¿Qué hizo Jesús cuando llegaron los niños?','¿Cómo podemos acoger a un compañero que está solo?'],activity:'Colorea la escena y explica qué gesto de Jesús te llama la atención. Representa con tu familia una situación en la que todos puedan participar y sentirse acogidos.',evaluation:'Pide al niño que nombre una manera de acoger a otra persona. Valora su comprensión y participación, sin comparar su dibujo con el de otros.'}
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function material(g){return{text:`# ${g.title}\nGuía para padres y docentes · Edad sugerida: 5 a 9 años · 25 minutos\n## Objetivo\n${g.objective}\n## Antes de empezar\nPrepara una Biblia católica, lápices y el dibujo descargable. Lee ${g.reference} con el niño. Adapta el vocabulario a su edad.\n## Comprendemos el Evangelio\n${g.explanation}\n## Actividad propuesta\n${g.activity}\n## Conversamos\n${g.questions.map(q=>'- '+q).join('\n')}\n## Comprobamos lo aprendido\n${g.evaluation}\n## Cierre\nInvita a un momento de silencio y agradecimiento personal. Las actividades de esta guía son propuestas pedagógicas.\n## Dibujo para colorear\nhttps://www.catolicosgpt.com/ninos/guias/${g.slug}/dibujo.jpg`,sources:[{id:'F1',title:g.reference,url:g.source}]};}
function cards(){return `<section class="max-w-6xl mx-auto px-4 py-6"><h2 class="text-2xl font-bold text-maroon">Guías para aprender en familia</h2><p class="py-3">Lectura bíblica, dibujo JPG para colorear y actividades para padres y docentes. De 5 a 9 años.</p><div class="grid grid-cols-1 sm:grid-cols-2 gap-5">${guides.map(g=>`<a class="block bg-white border rounded-2xl p-5" href="/ninos/guias/${g.slug}"><img src="/ninos/guias/${g.slug}/dibujo.jpg" alt="${esc(g.title)}: dibujo católico para colorear" width="320" height="320" loading="lazy" style="width:100%;max-height:280px;object-fit:contain"><h3 class="font-bold text-xl mt-3">${g.title}</h3><p>${g.reference} · Ver guía y descargar</p></a>`).join('')}</div></section>`;}
function register(app,render){
 app.get('/ninos/guias/:slug/dibujo.jpg',(req,res)=>{const g=guides.find(g=>g.slug===req.params.slug);if(!g)return res.sendStatus(404);res.set('Cache-Control','public,max-age=86400');if(req.query.download==='1')res.attachment(g.slug+'.jpg');res.type('jpg').sendFile(path.join(__dirname,'assets/guias',g.slug+'.jpg'));});
 app.get('/ninos/guias/:slug/descargar/:format',async(req,res)=>{const g=guides.find(g=>g.slug===req.params.slug);const f=req.params.format;if(!g||!['pdf','docx'].includes(f))return res.sendStatus(404);try{const buffer=await docs[f==='pdf'?'pdf':'word'](material(g));res.attachment(g.slug+'.'+f).send(buffer);}catch{res.sendStatus(500);}});
 app.get('/ninos/guias/:slug',(req,res)=>{const g=guides.find(g=>g.slug===req.params.slug);if(!g)return res.sendStatus(404);const body=`<article class="max-w-4xl mx-auto px-5 py-8"><a href="/ninos">Volver a Niños</a><h1 class="text-3xl font-bold mt-5">${g.title}</h1><p class="py-4">Guía para padres y docentes · 5 a 9 años · 25 minutos</p><p>${g.objective}</p><div class="flex flex-wrap gap-4 py-5"><a href="/ninos/guias/${g.slug}/dibujo.jpg?download=1" download>Descargar dibujo JPG</a><a href="/ninos/guias/${g.slug}/descargar/pdf">Descargar guía PDF</a><a href="/ninos/guias/${g.slug}/descargar/docx">Descargar guía Word</a></div><img src="/ninos/guias/${g.slug}/dibujo.jpg" alt="${g.title}, dibujo para colorear" width="1254" height="1254" style="width:100%;max-width:600px;height:auto;margin:20px auto"><h2 class="text-2xl font-bold mt-6">Leemos y comprendemos</h2><p class="py-3">Lee ${g.reference} en una Biblia católica con el niño.</p><p>${g.explanation}</p><h2 class="text-2xl font-bold mt-6">Actividad propuesta</h2><p class="py-3">${g.activity}</p><h2 class="text-2xl font-bold mt-6">Conversamos</h2><ul class="py-3">${g.questions.map(q=>`<li>${q}</li>`).join('')}</ul><h2 class="text-2xl font-bold mt-6">Lo que aprendimos</h2><p class="py-3">${g.evaluation}</p><p class="py-4">Fuente: <a href="${g.source}" target="_blank" rel="noopener noreferrer">${g.reference}</a>. Ilustración artística y actividades pedagógicas de CatólicosGPT.</p></article>`;
 res.send(render(`${g.title}: guía y dibujo para colorear | CatólicosGPT`,body,req,{description:`${g.title}: guía infantil con lectura de ${g.reference}, actividades y dibujo JPG para colorear. Descarga en Word y PDF.`,canonical:`/ninos/guias/${g.slug}`}));});
}
module.exports={register,cards,guides,material};
