const {test}=require('node:test');const assert=require('node:assert/strict');
const agent=require('../catholic-agent');const docs=require('../agent-documents');
const {PDFDocument}=require('pdf-lib');
function fixture({failure=false,noCitations=false,loop=false}={}){let openai=0;const requests=[];return{requests,fetcher:async(url,options)=>{const body=JSON.parse(options.body);requests.push({url,body});if(failure&&url.includes('magisterium'))return{ok:false,status:503};let data;if(url.endsWith('/search'))data={data:{results:[]}};else if(url.includes('magisterium'))data={choices:[{message:{content:'Jesús recibe a los niños.'}}],citations:noCitations?[]:[{document_title:'Evangelio según san Marcos',document_reference:'10, 13-16',cited_text:'Jesús bendice a los niños.',source_url:'https://bible.usccb.org/bible/mark/10'}]};else{openai++;data=(openai===1||loop)&&body.tools?{output:[{type:'function_call',name:'consultar_magisterium',call_id:`call${openai}`,arguments:JSON.stringify({query:'Fundamento en Marcos',category:'magisterial'})}]}:{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'# Resumen\nJesús recibe a los niños [F1]. Referencia inválida [F99].'}]}]};}return{ok:true,json:async()=>data};}};}
test('retrieves evidence, executes follow-up, deduplicates citations and removes unknown IDs',async()=>{const f=fixture();const result=await agent.run({query:'Resume el pasaje',mode:'resumen',signal:AbortSignal.timeout(5000),fetcher:f.fetcher});assert.equal(result.researchCalls,2);assert.equal(result.sources.length,1);assert(!result.text.includes('[F99]'));assert.equal(f.requests[0].body.numResults,6);assert.equal(f.requests[1].body.model,'magisterium-1');assert(f.requests.find(r=>r.body.input?.some(x=>x.type==='function_call_output')));});
test('never calls OpenAI if Magisterium fails',async()=>{const f=fixture({failure:true});await assert.rejects(agent.run({query:'Fe',signal:AbortSignal.timeout(5000),fetcher:f.fetcher}));assert(f.requests.every(r=>!r.url.includes('openai')));});
test('research budget remains bounded',async()=>{const f=fixture({loop:true});const r=await agent.run({query:'Fe',signal:AbortSignal.timeout(5000),fetcher:f.fetcher});assert.equal(r.researchCalls,3);assert.equal(f.requests.filter(x=>x.url.includes('openai')).length,3);});
test('missing structured sources is disclosed',async()=>{const f=fixture({noCitations:true});const r=await agent.run({query:'Fe',signal:AbortSignal.timeout(5000),fetcher:f.fetcher});assert.match(r.text,/no devolvió referencias/);});
test('untrusted source URLs cannot become executable links',()=>{assert.equal(agent.safeUrl('javascript:alert(1)'),'');assert.equal(agent.safeUrl('data:text/html,test'),'');});
test('Word and PDF exports contain genuine files with tables and references',async()=>{const input={text:'# Guía de estudio\nUna explicación en español.\n| Tema | Idea |\n|---|---|\n| Fe | Confianza |',sources:[{id:'F1',title:'Marcos',reference:'10, 13-16',url:'https://bible.usccb.org/bible/mark/10'}]};const word=await docs.word(input);assert.equal(word.subarray(0,2).toString(),'PK');const pdf=await docs.pdf(input);assert.equal(pdf.subarray(0,4).toString(),'%PDF');assert.equal((await PDFDocument.load(pdf)).getPageCount(),1);assert.throws(()=>docs.material({text:'x'.repeat(40001)}));});
test('large tables paginate without an infinite loop',async()=>{const pdf=await docs.pdf({text:'| Tema | Detalle |\n|---|---|\n'+Array.from({length:70},(_,i)=>`| ${i} | ${'Texto de formación '.repeat(20)} |`).join('\n')});assert((await PDFDocument.load(pdf)).getPageCount()>1);});
test('budget persists reservations, reconciles usage, and enforces a ceiling',()=>{
 const fs=require('fs'),os=require('os'),path=require('path');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cgpt-budget-'));const {createBudget}=require('../agent-budget');const old=process.env.OPENAI_AGENT_MONTHLY_BUDGET_USD;
 try{process.env.OPENAI_AGENT_MONTHLY_BUDGET_USD='.01';const budget=createBudget(dir);const reservation=budget.reserve({model:'gpt-4.1-mini',input:'Hola',max_output_tokens:100});reservation.settle({input_tokens:100,output_tokens:50});let state=JSON.parse(fs.readFileSync(path.join(dir,'agent-budget.json')));assert.equal(Object.values(state.months)[0].input,100);assert.throws(()=>createBudget(dir).reserve({model:'gpt-4.1-mini',input:'x'.repeat(100000),max_output_tokens:2800}),/budget_exhausted/);assert.throws(()=>budget.reserve({model:'unknown-expensive-model',input:'Hola',max_output_tokens:100}),/unpriced_model/);fs.writeFileSync(path.join(dir,'agent-budget.json'),'bad');assert.throws(()=>budget.admit('test'),/budget_store_invalid/);}finally{if(old===undefined)delete process.env.OPENAI_AGENT_MONTHLY_BUDGET_USD;else process.env.OPENAI_AGENT_MONTHLY_BUDGET_USD=old;fs.rmSync(dir,{recursive:true,force:true});}
});
test('sitemap excludes unpublished resources, deduplicates URLs and has no fabricated lastmod',()=>{const xml=require('../seo-module').generateSitemapXML({infografias:[{slug:'hidden',publicado:false},{slug:'test&one',publicado:true}],authorityPages:[{path:'/ninos'},{path:'/ninos'}]});assert(!xml.includes('/hidden'));assert(xml.includes('test&amp;one'));assert.equal(xml.match(/<loc>[^<]*\/ninos<\/loc>/g).length,1);assert(!xml.includes('<lastmod>'));});
